### ISSUE TITLE
allow wildcards in file cli arguments

### ISSUE THREAD

**Issue by willmorrison1** [actris-cloudnet/halo-reader#5]
Hello, and thanks for the reader and the ongoing work. I notice in the readme the use of fle wildcards in the cli e.g.

```
haloreader from_raw Stare_213_20230326_*.hpl Background_*0323-*.txt -o out.nc --plot
```

but this is not supported in the code. 

I have a PR ready with this capability - happy to contribute but there is no write access.

**Comment by nikoleskinen** [comment]
Hi, you need to make [pull request from fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by willmorrison1** [comment]
Great, yes, got it. Moved to PR https://github.com/actris-cloudnet/halo-reader/pull/6
